<%@ page contentType = "text/html; charset=UTF-8"%>

<div data-role="navbar" data-iconpos="top">
    <ul>
        <li>
            <a href="main_page2.jsp" data-transition="fade" data-theme="" data-icon="home">
                main
            </a>
        </li>
        <li>
            <a href="artist2.jsp" data-transition="fade" data-theme="" data-icon="star">
                artist
            </a>
        </li>
        <li>
            <a href="junsi2.jsp" data-transition="fade" data-theme="" data-icon="search">
                show
            </a>
        </li>
        <li>
            <a href="digital2.jsp" data-transition="fade" data-theme="" data-icon="info">
                utube
            </a>
        </li>
        <li>
            <a href="last2.jsp" data-transition="fade" data-theme="" data-icon="arrow-l">
                last
            </a>
        </li>
    </ul>
</div>